jQuery(function($){isMobile=false;if(/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|ipad|iris|kindle|Android|Silk|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm(os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows (ce|phone)|xda|xiino/i.test(navigator.userAgent)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s)|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp(i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac(|\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt(|\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg(g|\/(k|l|u)|50|54|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v)|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v)|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-|)|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|yas\-|your|zeto|zte\-/i.test(navigator.userAgent.substr(0,4))||window.innerWidth<981){isMobile=true;}
var clockExist=document.getElementsByClassName("clock");var today;var configDate;var futs=[];var obj=[];var displayAsText=document.getElementsByClassName("display_text");var currClockGlobal=[];function getTodayDate(){today=new Date();return today;}
function dateToUtc(today){var nowUtc=new Date(today.getTime()+(today.getTimezoneOffset()*60000));return nowUtc;}
function setClock(currClock){configDate=currClock.attr("data-expire-date");var bits=configDate.split(/\D/);var configDateInt=new Date(bits[0],--bits[1],bits[2],bits[3],bits[4]);var afterTomorrow=(new Date(configDateInt))>(new Date(new Date().getTime()+60*60*24*1000));if(configDate!=""){futs.push(new Date((new Date(configDateInt)).getTime()-(today.getTimezoneOffset()*60000)));obj.push({});}else{var end=new Date();end.setHours(23,59,59,999);futs.push(new Date(end.getTime()-(end.getTimezoneOffset()*60000)));obj.push({});}
if(afterTomorrow){currClock.addClass('long');}}
function intSpl(i){i=Math.floor(i);return[~~(i/10),i%10];}
function drawTime(){for(j=0;j<clockExist.length;j++){var now=new Date().getTime(),dif=now<futs[j]?Math.floor((futs[j]-now)/1000):0;obj[j].s=intSpl(dif%60);obj[j].m=intSpl(dif/60%60);obj[j].h=intSpl(dif/60/60%24);obj[j].h=intSpl(dif/60/60%24);obj[j].d=intSpl(dif/60/60/24);for(var key in obj[j]){if(obj[j].hasOwnProperty(key)){for(var i=0;i<2;i++){$('#'+key+i).css({backgroundPosition:-obj[j][key][i]*11});if(displayAsText[0])currClockGlobal[j].find('#'+key+i).text(obj[j][key][i]);}}}}}
if(clockExist){$(".clock").each(function(){getTodayDate();setClock($(this));currClockGlobal.push($(this));});drawTime();setInterval(drawTime,1000);}
var bodyPaddingTop=parseInt($("body").css("padding-top").replace("px",""))-10+"px";$("#secondary-header .main-nav").css("margin-top",bodyPaddingTop);$("#hamburger").click(function(){$("#secondary-header .main-nav").toggleClass("show");});$(".more-info").click(function(){$("html").css("overflow-y","hidden");});$('.modal').click(function(e){if(e.target!==this)
return;else $("html").css("overflow-y","auto");});$(".close").click(function(){$("html").css("overflow-y","auto");});$(".lang_bar #currentLanguage").click(function(){event.preventDefault();$(".lang_bar #lang_bar_inner").toggleClass("showInner");$(".lang_bar #dropDownArrow").toggleClass("open");});var domain=(window.location.hostname).split(".");var innerPage=(window.location.href).split("com/")[1]
innerPage=innerPage.indexOf("?setCookie")>-1?innerPage.replace("?setCookie",""):innerPage;domain=domain[1]+"."+domain[2];$(".availableLanguage").click(function(e){e.preventDefault();redirectByLanguage($(this).attr("id"),$(this).attr("href"));});function redirectByLanguage(lang,newHref){var cookieIsSet=false;var newWindowLocation=newHref+innerPage+"?setCookie";var date=new Date();date.setTime(date.getTime()+(1000*24*60*60*1000));document.cookie="geo_language="+lang+"; expires="+date.toGMTString()+"; domain="+domain+"; path=/";while(!cookieIsSet){if(checkCookie(lang,newWindowLocation))cookieIsSet=true;}}
function checkCookie(lang,newWindowLocation){var cookieValue=getCookieByName("geo_language");if(lang==cookieValue){window.location.replace(newWindowLocation);return true;}
return false;}
function getCookieByName(name){var value="; "+document.cookie;if(value.indexOf(name)>-1){value=value.split("; "+name+"=");return value[1].split(";")[0];}
else return"";}
var currDomain=document.location.href.split(".com/");currDomain=currDomain[0]+".com/";if((currDomain).indexOf("https://es")>-1){$("div").filter(function(){if($(this).css('background-image')!="none"&&$(this).css('background-image').indexOf("url")>-1){var bgImage=$(this).css('background-image').split(".com/")[1].replace('"',"").replace(")","");bgImage=currDomain+bgImage;$(this).css("background-image","url('"+bgImage+"') !important");}});$("img").each(function(){if(!$(this).parent().parent().parent().is("#ceg-20962e76-1afc-488c-844f-9a67fb413577")){var src=$(this).attr("src");var srcset=$(this).attr("srcset")
if(src.indexOf(".com")>-1){src=currDomain+src.split(".com/")[1];$(this).attr("src",src);}
if(srcset){srcset=srcset.replace("spinsamba",currDomain);srcset=srcset.replace("casinomidas",currDomain);srcset=srcset.replace("jackmillion",currDomain);$(this).attr("srcset",srcset);}}});}
var currHref=$("body.iframe #logo a").attr("href");$("body.iframe #logo a").attr("href",currHref+"/lobby");$("#logo img").addClass("puffIn magictime");if($("body").hasClass("page")){window.__lc=window.__lc||{};window.__lc.license=8789641;(function(){var lc=document.createElement('script');lc.type='text/javascript';lc.async=true;lc.src=('https:'==document.location.protocol?'https://':'http://')+'cdn.livechatinc.com/tracking.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(lc,s);})();}
$(".chat_parrot img").click(function(){$(this).css("display","none");$("#chat-widget-container").addClass("open");});$(".chat_icon_image").click(function(){$("#chat-widget-container").addClass("open");});$("body.iframe:not(.logged-in) .play_now").click(function(){event.preventDefault();window.parent.location=document.referrer+"lobby.aspx?show=login";});var styleChanged=false;var chatStylechangeObserver=new MutationObserver(function(mutations){mutations.forEach(function(e){var height=parseInt((e.target.style.height).replace("px",""));if(height>300&&!styleChanged){var css="#chat-widget-container.open { height:"+e.target.style.height+" !important; }";var head=document.head||document.getElementsByTagName('head')[0];var style=document.createElement('style');head.appendChild(style);style.type='text/css';if(style.styleSheet){style.styleSheet.cssText=css;}else{style.appendChild(document.createTextNode(css));}
styleChanged=true;}});});var checkInterval=setInterval(checkIfExists,100);function checkIfExists(){target=document.getElementById("chat-widget-container");if(target){chatStylechangeObserver.observe(target,{attributes:true,attributeFilter:['style']});clearInterval(checkInterval);return true;}
return false;}
if(document.getElementsByClassName("signup-btn")[0]){setTimeout(function(){lobyLink=document.getElementsByClassName("signup-btn")[0].href;$(".vip_banner a.yellow").each(function(){$(this).attr("href",lobyLink);});},200);}
$("body.au .lobby-link, .vip-bullets .button.yellow").click(function(event){if($(this).attr("href").indexOf("signup")>-1){event.preventDefault();if(!document.getElementById("disabled-signup")){var element=document.createElement("div");element.setAttribute("id","disabled-signup");element.style.display="none";element.innerHTML="<div id='disabled-signup-inner'><p>Unfortunately we're not accepting players from your country</p><button onClick='hideDisabledSignup()' class='button yellow'>Close</button></div>";document.body.appendChild(element);}
$("#disabled-signup").show();$("#disabled-signup-inner button").click(function(){$("#disabled-signup").hide();});}});if((window.location.href.indexOf("spinsamba")!==-1)&&window.width<1025){screen.orientation.lock('portrait');}
function equalizeButtonWidth(buttonSelector,buttonSelector2){var headerButtonWidthArray=[];headerButtonWidthArray.push($(buttonSelector).outerWidth());headerButtonWidthArray.push($(buttonSelector2).outerWidth());var headerButtonWidth=Math.max.apply(null,headerButtonWidthArray);$(buttonSelector).css({"width":headerButtonWidth+"px","padding-left":"0px","padding-right":"0px"});$(buttonSelector2).css({"width":headerButtonWidth+"px","padding-left":"0px","padding-right":"0px"});}
if(!isMobile&&$(".login-head"))equalizeButtonWidth(".login-btn",".signup-btn");var languageClass=((window.location.href).split("//")[1]).split(".")[0];$("body").addClass(languageClass);function getCookie(name){const value=`; ${document.cookie}`;const parts=value.split(`; ${name}=`);if(parts.length===2)return parts.pop().split(';').shift();}
getUserScore=function(postId){var username=$(".username-field#user"+postId).val();var currency=(new URLSearchParams(window.location.search)).get("currency");currency=currency?currency.substr(0,3):null;$(".user"+postId+".check-score").prop("disabled",true);$(".user"+postId+".score-result").html("");$(".user"+postId+".score-result-title").html("");$(".user"+postId+".score-result-image").html("");$(".user"+postId+".score-result-image").removeClass('left');$(".user"+postId+".score-result-title").removeClass('right');$(".user"+postId+".no-position-score").hide();$(".user"+postId+".score-result-fail").hide();$(".user"+postId+".loader-score").show();$(".user"+postId+".no-points-score").hide();$.ajax({type:'GET',url:"/api/brand-utils/check-leaderboard-score?pid="+postId+"&username="+username+(currency?("&currency="+currency):""),data:{format:'json'},error:function(e){$(".user"+postId+".score-result.points-score").html("0");$(".user"+postId+".score-result-fail").show();$(".user"+postId+".no-position-score").show();},success:function(data){if(data.success){switch(data.type){case"points":if(data.score>0){$(".user"+postId+".score-result.points-score").html(data.score);}
else{$(".user"+postId+".no-points-score").show();}
break;case"group":$(".user"+postId+".group-progress-bar").addClass('hide_progress_bar');$(".user"+postId+".score-result-title").html(data.group_text);if((data.group_image!==""&&data.group_image!=null)&&(data.group_text!==undefined&&data.group_text!=null)){var img=new Image();var div=$(".user"+postId+".score-result-image");img.onload=function(){div.append(img);};img.src=data.group_image;var g_progress=Math.round(data.group_progress);console.log(data.last_group);if(data.last_group!='lastGroup'&&g_progress>0){$(".user"+postId+".group-progress-bar").removeClass('hide_progress_bar');var progress_message="Get to the next level! Your progress below:";var language=getCookie("geo_language");if($("body").hasClass("es"))progress_message="Avanza al siguiente nivel! Tu progreso actual:";if($("body").hasClass("it"))progress_message="Sali al prossimo livello! Di seguito I tuoi progressi:";if($("body").hasClass("de"))progress_message="Komm auf die nächste Stufe! Ihr Fortschritt unten:";$(".user"+postId+".group-progress-bar .progress-message").text(progress_message);var css="@keyframes progress {0% { width: 10%;} 100% {width: "+g_progress+"%;box-shadow: 0 0 10px #3feb6d;}} @keyframes p {90%,100% {--p: "+g_progress+";}} .progress-moved .progress-bar2 {animation: progress 5s forwards;}  .loader {--p: 0; animation: p 5s steps(100) forwards;}";head=document.head||document.getElementsByTagName('head')[0],style=document.createElement('style');head.appendChild(style);style.type='text/css';if(style.styleSheet){style.styleSheet.cssText=css;}else{style.appendChild(document.createTextNode(css));}}}
else{$(".user"+postId+".score-result-fail").show();}
break;case"position":if(data.position===""||data.position>100){$(".user"+postId+".no-position-score").show();}else{$(".user"+postId+".position-score.score-result").html(data.position);}
break;default:$(".user"+postId+".score-result").html(data.score);}}else{$(".user"+postId+".group-progress-bar").addClass('hide_progress_bar');$(".user"+postId+".score-result-fail").show();$(".user"+postId+".no-position-score").show();$(".user"+postId+".no-points-score").show();}},complete:function(){$(".user"+postId+".loader-score").hide();$(".user"+postId+".check-score").prop("disabled",false);if(!isMobile){var promotion=$("#user"+postId).closest(".promotion");var promoHeight=promotion.children(".promotion_inner")[0].offsetHeight;if(promotion.hasClass("marginRight"))promotion.next().children(".promotion_inner")[0].style.height=promoHeight+"px";else promotion.prev().children(".promotion_inner")[0].style.height=promoHeight+"px";}},dataType:'json'});};});jQuery(document).ready(function(){jQuery('.nl .term_icon').each(function(index){if(jQuery(this).attr('href')===undefined){}
else{if(jQuery(this).attr('href').indexOf('curacao')>=0){jQuery(this).hide();}}});});